apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
spec:
  selector:
    matchLabels:
      app: mysql8
  strategy:
     type: Recreate
  template:
    metadata:
      labels:
        app: mysql8
    spec:
       containers:
       - image: mysql:8.0
         name: mysql
         envFrom:
           - secretRef:
               name: app-secret
         ports:
         - containerPort: 3306
         volumeMounts:
         - mountPath: "/etc/mysql/"
           readOnly: true
           name: conf
         - mountPath: "/var/lib/mysql"
           name: data
       volumes:
       - name: mysql-local-storage
         persistentVolumeClaim:
           claimName: mysql-pv-claim
       - name: conf     
         configMap:
          name: mysql-conf
          items:
            - key: my.cnf
              path: my.cnf
            - key: mysql.cnf
              path: conf.d/mysql.cnf
            - key: docker.cnf
              path: conf.d/docker.cnf
       - name: data
         persistentVolumeClaim:
            claimName: mysql8-claim
       securityContext:
          runAsUser: 999
          fsGroup: 999
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql8
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: 10.105.44.55
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  labels:
    app: mysql8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
