apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/sharedfolder
    server: 172.17.0.1
