apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    app: mysql8
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/mysql
    server: 172.17.0.1
