apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql8-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: mysql8
