apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18.0
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-volume
        - mountPath: /etc/nginx/conf.d/ # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: conf
      volumes:
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: nginx-claim
      - name: conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: site.conf
              path: site.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    # Create endpoints also if the related pod isn't ready
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31313
    targetPort: 80
  selector:
    app: nginx

